[versions]
agp = "8.1.1"
kotlin = "1.8.10" # Also increase ksp version accordingly
ksp = "1.8.10-1.0.9" # Also increase ksp version accordingly
kotlin-coroutines = "1.7.1"
detekt = "1.22.0"
hilt = "2.47"
retrofit = "2.9.0"
compose-destinations = "1.8.39-beta"
composeBom = "2023.06.00"
media3 = "1.1.1"
accompanist = "0.28.0"
moshi = "1.14.0"
coil = "2.4.0"
lifecycle = "2.6.1"

[plugins]

[libraries]

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }

#AndroidX
androidx-core = { module = "androidx.core:core-ktx", version = "1.10.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.7.2" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.6.1" }
androidx-appStartup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidx-workManager = { module = "androidx.work:work-runtime-ktx", version = "2.8.1" }
androidx-constraintLayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.1" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

#Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material = { module = "androidx.compose.material:material" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.7.2" }

#Material - used to set applicaitons xml theme
androidx-material = { module = "com.google.android.material:material", version = "1.9.0" }

#  Retrofit
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version = "4.11.0" }

#Moshi
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-annotationProcessor = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

#  Hilt
hilt-gradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-kaptCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-composeNavigation = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
hilt-androidxCompiler = { module = "androidx.hilt:hilt-compiler", version = "1.0.0" }
hilt-workManager = { module = "androidx.hilt:hilt-work", version = "1.0.0" }

# Room
paging3-runtime = { module = "androidx.paging:paging-runtime", version = "3.2.0" }
paging3-compose = { module = "androidx.paging:paging-compose", version = "3.2.0" }
androidx-paging-core = { module = "androidx.paging:paging-common-ktx", version = "3.2.0" }

# Messenger Chat
sports-messenger = { group = "com.onetwenty.sports.messenger", name = "sports-messenger", version = "0.19" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "32.2.3" }
firebase-common-ktx = { module = "com.google.firebase:firebase-common-ktx", version = "20.3.3" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx", version = "23.2.1" }

# 3rd Party Lib to provide composable-scoped hiltViewModels
resaca-hilt = { module = "com.github.sebaslogen.resaca:resacahilt", version = "2.4.3" }

# Compose Destinations
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations" }
compose-destinations-animation-core = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }

# Dependencies of the convention plugins
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
kapt-gradlePlugin = { group = "org.jetbrains.kotlin.kapt", name = "org.jetbrains.kotlin.kapt.gradle.plugin", version.ref = "kotlin" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }

# Timber logger
timber-logger = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

# Accompanist System UI Controller
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }

# Accompanist WebView
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version = "0.30.1" }

# Accompanist Permissions
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version = "0.30.1" }

# Coil
coil = { module = "io.coil-kt:coil", version = "2.4.0" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

# Android desugaring (in order to use java.time in min api 24)
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.3" }

# Steaming-Player
theo-sdk = { group = "com.theoplayer.theoplayer-sdk-android", name = "core", version = "5.11.0" }
theo-sdk-ads = { group = "com.theoplayer.theoplayer-sdk-android", name = "integration-ads-ima", version = "5.+"  }

[bundles]
compose = ["compose-runtime", "compose-material", "compose-material3", "compose-tooling", "compose-foundation", "compose-tooling-preview"]
coil = ["coil-compose", "coil-svg"]
